#!/bin/bash
#
# This script contains specific config variables for use with
#  the launch.sh script.

# Debug?
DEBUG=y

#
# Setup some specific values for EC2 here.
#
EC2_AMI=ami-05355a6c               # This is Amazon Linux 2013.03, x86_64 in US East
EC2_INSTANCE_TYPE=t1.micro         # Size of the instance to launch
EC2_KEYNAME=parrott-ec2            # The key to use 
EC2_SECURITY_GROUP=webserver       # Security group which allows for Web & SSH access

# 
# Select the bootstrap script/data to use 
#
BOOTSTRAP=bootstrap/simple-web.sh
